# Generated by Django 4.0.4 on 2022-05-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactmsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbfullName', models.CharField(max_length=50)),
                ('dbemail', models.CharField(max_length=50)),
                ('dbmessage', models.TextField()),
            ],
        ),
    ]
